### ISSUE TITLE
Logo PHPID

### ISSUE THREAD

**Issue by peterjkambey** [phpid-jakarta/www-smesummit.id-2019#22]
Logo Baru:
![logobaru](https://user-images.githubusercontent.com/1121775/48704756-f7ccab80-ec29-11e8-8c80-cf23452c8bf9.png)

Logo Lama:
![php indonesia](https://user-images.githubusercontent.com/1121775/48704793-0ca93f00-ec2a-11e8-9a1a-2768b7f13073.jpg)

Untuk saat ini dua2nya masih valid, tahun depan mulai start pake logo baru...

**Comment by mazipan** [comment]
Untuk logo paling atas nanti kita pake yang dari om Kresna, ini untuk di footer aja berarti.
Pake logo baru aja lah 👌

**Comment by mazipan** [comment]
Updated in website ya.
Sudah di attach di project juga.
