### ISSUE TITLE
[Backend] save new sponsor data

### ISSUE THREAD

**Issue by mazipan** [phpid-jakarta/www-smesummit.id-2019#23]
Columns: 
  - Nama Perusahaan
  - Logo
  - Sektor Perusahaan
  - Email PIC
  - Handphone/WA/TG PIC
  - Sponsor Type (Platinum/Gold/Silver)

**Comment by ammarfaizi2** [comment]
Done https://github.com/phpid-jakarta/api-smesummit.id-2019/pull/8
