### ISSUE TITLE
Request to add bookmark

### ISSUE THREAD

**Issue by peterjkambey** [phpid-jakarta/www-smesummit.id-2019#38]
Request for add bookmark page for easier sharing for instance,

www.smesummit.id/#volunteer
www.smesummit.id/#sponsor

this bookmark will directly follow to related section of the main page.. 
thank's

**Comment by mazipan** [comment]
Ini bisa juga di share langsung ke page nya aja om @peterjkambey

www.smesummit.id/volunteer
www.smesummit.id/sponsor
