### ISSUE TITLE
The API for speaker registration is now ready to use

### ISSUE THREAD

**Issue by ammarfaizi2** [phpid-jakarta/www-smesummit.id-2019#55]
Hello,

I have finished the speaker registration API. I also tested the API and it is now working properly, the API procedure usage is the same with others, you can now implement it to the speaker registration page. Please have a check the API from your end.

Do not hesitate to contact me if you have any problem with this.

Thank You

## Get Token
```
https://api.smesummit.id/speaker_register.php?action=get_token
```
## Captcha
```
https://api.smesummit.id/captcha.php?token=${token}
```

## Submit
```
https://api.smesummit.id/speaker_register.php?action=submit
```

## Required Fields to be Submitted
```json
[
    "name",
    "company_name",
    "position",
    "email",
    "photo",
    "last_education",
    "experience",
    "phone",
    "sector",
    "topic",
    "captcha"
]
```

**Comment by mazipan** [comment]
Should be okay now in https://www.smesummit.id/speaker/.
Help to test drive ya.
